resolver: lts-18.27
packages:
  - .

extra-deps:
- hashable-1.3.5.0
- rest-rewrite-0.3.0
- git: https://github.com/facundominguez/liquidhaskell.git
  commit: 4c354c4d099f6fa47b624a857fca45f0a105fb01
  subdirs:
    - .
    - liquid-base
    - liquid-containers
    - liquid-ghc-prim
    - liquid-prelude
- git: https://github.com/facundominguez/liquid-fixpoint.git
  commit: 07d95d82ddd72d8484044ab3097c189ce87cf76e
allow-newer: true

nix:
  packages: ["z3"]
