resolver: lts-17.2
packages:
  - .
extra-deps:
  - ../liquidhaskell
  - ../liquidhaskell/liquid-base
  - ../liquidhaskell/liquid-containers
  - ../liquidhaskell/liquid-prelude
  - ../liquidhaskell/liquid-ghc-prim
  - ../liquidhaskell/liquid-fixpoint

allow-newer: true